apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    run: weather
spec:
  type: NodePort
  ports:
  - nodePort: 31200
    port: 8080
    targetPort: 8000
    protocol: TCP
  selector:
    app: weather 
  type: LoadBalancer
  externalIPs:
  - 3.34.74.50
