apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  labels:
    app: mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mario
  labels:
    run: mario
spec:
  type: NodePort
  ports:
  - nodePort: 31001
    port: 8000
    targetPort: 8080
    name: http
  selector:
    app: mario
