apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: minecraft-volume
              mountPath: /data
      volumes:
        - name: minecraft-volume
          persistentVolumeClaim:
            claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
  type: LoadBalancer
